### **Getting dataset with ability to detremine Frames length**

In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM , Bidirectional , GRU
import numpy as np
import random
from sklearn.model_selection import train_test_split
import pandas as pd

In [3]:
num_sampel = 60
all_arr_train_datasets =[]
all_arr_label_datasets =[]


In [4]:
json_files_names = [
    'class_0_normal_datase_1.json', 
    'class_0_normal_datase_2.json',
    'class_0_normal_datase_3.json', 
    'class_0_normal_datase_4.json' ,

'class_1_elbow_up_datase_1.json',
'class_1_elbow_up_datase_2.json',
'class_1_elbow_up_datase_3.json',
'class_1_elbow_up_datase_4.json',

    'class_2_hand_faced_datase_1.json',
    'class_2_hand_faced_datase_2.json',
    'class_2_hand_faced_datase_3.json',
    'class_2_hand_faced_datase_4.json',
]

In [5]:
# Repeting times:
for _ in range(4):
    # gener arrays that use to do data agumentation
    agu_arrays = []

    x1_large = np.random.randint(160,370)
    x2_large = np.random.randint(160,370)
    y1_large = np.random.randint(160,370)
    y2_large = np.random.randint(160,370)

    x1_smill = np.random.randint(5,95)
    x2_smill = np.random.randint(5,95)
    y1_smill = np.random.randint(5,95)
    y2_smill = np.random.randint(5,95)

    arr_x_y_large = np.array([x1_large,y1_large,x1_large,y1_large,x1_large,y1_large,x1_large,y1_large,x1_large,y1_large,x1_large,y1_large,x1_large,y1_large,x1_large,y1_large,x1_large,y1_large,x1_large,y1_large,x1_large,y1_large])
    agu_arrays.append(arr_x_y_large)
    arr_x_y_smill = np.array([x1_smill,y1_smill,x1_smill,y1_smill,x1_smill,y1_smill,x1_smill,y1_smill,x1_smill,y1_smill,x1_smill,y1_smill,x1_smill,y1_smill,x1_smill,y1_smill,x1_smill,y1_smill,x1_smill,y1_smill,x1_smill,y1_smill])
    agu_arrays.append(arr_x_y_smill)
    arr_x_large = np.array([x2_large,0,x2_large,0,x2_large,0,x2_large,0,x2_large,0,x2_large,0,x2_large,0,x2_large,0,x2_large,0,x2_large,0,x2_large,0])
    agu_arrays.append(arr_x_large)
    arr_x_smill = np.array([x2_smill,0,x2_smill,0,x2_smill,0,x2_smill,0,x2_smill,0,x2_smill,0,x2_smill,0,x2_smill,0,x2_smill,0,x2_smill,0,x2_smill,0])
    agu_arrays.append(arr_x_smill)
    arr_y_large = np.array([0,y2_large,0,y2_large,0,y2_large,0,y2_large,0,y2_large,0,y2_large,0,y2_large,0,y2_large,0,y2_large,0,y2_large,0,y2_large,0,y2_large])
    agu_arrays.append(arr_y_large)
    arr_y_smill = np.array([0,y2_smill,0,y2_smill,0,y2_smill,0,y2_smill,0,y2_smill,0,y2_smill,0,y2_smill,0,y2_smill,0,y2_smill,0,y2_smill,0,y2_smill])
    agu_arrays.append(arr_y_smill)


    #===========================================================================
    # Loop to get agumented data  ===> this loop must run two times,
    #  one for adding data,  second for reduce data after re run previouse agu_arrays
    #============================================================================
    for agu_arr in agu_arrays:
        # Loop trough all json files 
        for json_file_name in json_files_names:    
            try:
                print(json_file_name)
                df =  pd.read_json(f'./dataset/{json_file_name}')
                train_column = df.loc[:,'data_rows']
                label_column = df.loc[: , 'training_label']

                # convert all list inside dataset to numpy array:
                arr_dataset = []
                for data_row in train_column:
                    new_data_row = np.array(data_row) + agu_arr # this line must be change every time we re-run after re-generat augented data 
                    arr_dataset.append(data_row)

                # show shpae:
                arr_dataset = np.array(arr_dataset)
                arr_dataset.shape

                # Create temporary tow arrays
                tem_arr_train_dataset = []
                tem_arr_label_dataset = []

                # Basic Setting
                num_package = int(len(arr_dataset)/num_sampel)
                print(num_package)
                start =  0
                end = num_sampel

                # Loop to make Backages
                for _ in range(num_package):
                    curr_arr = np.array(arr_dataset[start:end])
                    if len(curr_arr) == num_sampel:
                        tem_arr_train_dataset.append(curr_arr)
                        start +=  num_sampel
                        end +=  num_sampel

                # Abbend all data to final arrays (all_arr_train_datasets and all_arr_label_datasets)
                for inx , data in  enumerate(tem_arr_train_dataset):
                    all_arr_train_datasets.append(np.array(data))
                    all_arr_label_datasets.append(np.array(label_column[0]))
            except:
                print(f"Not opened : {json_file_name}")



class_0_normal_datase_1.json
41
class_0_normal_datase_2.json
42
class_0_normal_datase_3.json
42
class_0_normal_datase_4.json
42
class_1_elbow_up_datase_1.json
41
class_1_elbow_up_datase_2.json
42
class_1_elbow_up_datase_3.json
41
class_1_elbow_up_datase_4.json
41
class_2_hand_faced_datase_1.json
41
class_2_hand_faced_datase_2.json
42
class_2_hand_faced_datase_3.json
42
class_2_hand_faced_datase_4.json
41
class_0_normal_datase_1.json
41
class_0_normal_datase_2.json
42
class_0_normal_datase_3.json
42
class_0_normal_datase_4.json
42
class_1_elbow_up_datase_1.json
41
class_1_elbow_up_datase_2.json
42
class_1_elbow_up_datase_3.json
41
class_1_elbow_up_datase_4.json
41
class_2_hand_faced_datase_1.json
41
class_2_hand_faced_datase_2.json
42
class_2_hand_faced_datase_3.json
42
class_2_hand_faced_datase_4.json
41
class_0_normal_datase_1.json
41
class_0_normal_datase_2.json
42
class_0_normal_datase_3.json
42
class_0_normal_datase_4.json
42
class_1_elbow_up_datase_1.json
41
class_1_elbow_up_datas

In [6]:
print(np.array(all_arr_train_datasets).shape)
print(np.array(all_arr_label_datasets).shape)

(9960, 60, 22)
(9960,)


In [7]:
print(np.unique(all_arr_label_datasets))

[0 1 2]


In [8]:
# Chick if all data has same count. Chick planace
print(np.sum(all_arr_label_datasets == np.array(0)))
print(np.sum(all_arr_label_datasets == np.array(1)))
print(np.sum(all_arr_label_datasets == np.array(2)))



3340
3300
3320


In [9]:
x_train, x_test, y_train, y_test = train_test_split(np.array(all_arr_train_datasets), np.array(all_arr_label_datasets), test_size=0.10, shuffle=True, random_state=42)
x_train, x_val, y_train, y_val = train_test_split(np.array(x_train), np.array(y_train), test_size=0.10, shuffle=True, random_state=42)

In [10]:
print(x_train.shape)
print(y_train.shape)
print(x_val.shape)
print(x_test.shape)

(8067, 60, 22)
(8067,)
(897, 60, 22)
(996, 60, 22)


In [11]:
np.unique(y_train)

array([0, 1, 2])

In [12]:
# model = Sequential()
# model.add(GRU(64, input_shape=(x_train.shape[1:]), activation='relu', return_sequences=True))
# model.add(Dropout(0.2))

# model.add(GRU(64, activation='relu'))
# model.add(Dropout(0.1))

# model.add(Dense(32, activation='relu'))
# model.add(Dropout(0.2))

# model.add(Dense(3, activation='softmax'))

2022-08-30 21:48:15.971081: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [15]:
model = Sequential()
model.add(GRU(64, input_shape=(x_train.shape[1:]), activation='relu', return_sequences=True))
model.add(Dropout(0.2))

model.add(GRU(64, activation='sigmoid' , return_sequences=True))
model.add(Dropout(0.1))

model.add(GRU(64, activation='sigmoid' , return_sequences=True))
model.add(Dropout(0.1))

model.add(GRU(64, activation='sigmoid'))
model.add(Dropout(0.1))


model.add(Dense(32, activation='sigmoid'))
model.add(Dense(32, activation='sigmoid'))
# model.add(Dense(32, activation='sigmoid'))
model.add(Dropout(0.2))

model.add(Dense(3, activation='softmax'))

In [16]:
opt = tf.keras.optimizers.Adam(lr=0.001, decay=1e-6)

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=opt,
    metrics=['accuracy'],
)

history = model.fit(x_train,
          y_train,
          epochs=20,
          validation_data=(x_val, y_val))

Epoch 1/20
253/253 [==============================] - 24s 78ms/step - loss: 1.0323 - accuracy: 0.4308 - val_loss: 0.5901 - val_accuracy: 0.6934
Epoch 2/20
253/253 [==============================] - 18s 70ms/step - loss: 1.0807 - accuracy: 0.4301 - val_loss: 1.0999 - val_accuracy: 0.3066
Epoch 3/20
253/253 [==============================] - 18s 70ms/step - loss: 1.1077 - accuracy: 0.3383 - val_loss: 1.0978 - val_accuracy: 0.3066
Epoch 4/20
253/253 [==============================] - 18s 72ms/step - loss: 0.7524 - accuracy: 0.5772 - val_loss: 0.5027 - val_accuracy: 0.6421
Epoch 5/20
253/253 [==============================] - 18s 72ms/step - loss: 0.6298 - accuracy: 0.6275 - val_loss: 0.4825 - val_accuracy: 0.6622
Epoch 6/20
253/253 [==============================] - 19s 75ms/step - loss: 0.4848 - accuracy: 0.6709 - val_loss: 0.6696 - val_accuracy: 0.6288
Epoch 7/20
253/253 [==============================] - 18s 73ms/step - loss: 0.5096 - accuracy: 0.6586 - val_loss: 0.4706 - val_accuracy:

In [17]:
model.evaluate(x_test ,  y_test)

32/32 [==============================] - 1s 17ms/step - loss: 0.0021 - accuracy: 1.0000


[0.0021262315567582846, 1.0]

In [42]:
for _  in range(40):    
    idx = np.random.randint(0,len(x_test))
    predict_result = model.predict(np.expand_dims(x_test[idx] , axis=0))
    print(predict_result)
    print(f"IDX = {idx}")
    print(np.argmax(predict_result))
    print(y_test[idx])

1/1 [==============================] - 0s 94ms/step
[[9.9674988e-01 2.9293001e-06 3.2471125e-03]]
IDX = 54
0
0
1/1 [==============================] - 0s 55ms/step
[[4.7244894e-06 9.9945897e-01 5.3624058e-04]]
IDX = 499
1
1
1/1 [==============================] - 0s 37ms/step
[[0.00123377 0.00106273 0.9977035 ]]
IDX = 149
2
2
1/1 [==============================] - 0s 38ms/step
[[9.9641031e-01 3.2015230e-06 3.5865381e-03]]
IDX = 150
0
0
1/1 [==============================] - 0s 35ms/step
[[9.9666756e-01 2.9959233e-06 3.3294137e-03]]
IDX = 503
0
0
1/1 [==============================] - 0s 41ms/step
[[4.738878e-06 9.994567e-01 5.385754e-04]]
IDX = 902
1
1
1/1 [==============================] - 0s 37ms/step
[[9.9674976e-01 2.9293278e-06 3.2472531e-03]]
IDX = 159
0
0
1/1 [==============================] - 0s 33ms/step
[[0.0011985  0.00114103 0.9976605 ]]
IDX = 178
2
2
1/1 [==============================] - 0s 35ms/step
[[9.9675328e-01 2.9264397e-06 3.2437253e-03]]
IDX = 347
0
0
1/1 [=========

In [22]:
file_path = f"./model_container/1"
model.save(filepath=file_path, save_format='tf')

INFO:tensorflow:Assets written to: ./model_container/1/assets


In [ ]:
docker run -p 8501:8501 --name RNN_model_pos_predection --mount type=bind,source=/Users/mohammed/Desktop/hand_on_machine_learing/pos_estimation/model_container/,target=/models/model_container -e MODEL_NAME=model_container -t tensorflow/serving

In [ ]:
# docker run -t --name RNN_model_pos_predection --rm -p 8501:8501 \
#     -v "/Users/mohammed/Desktop/hand_on_machine_learing/pos_estimation/model_container:/models/model_container" \
#     -e MODEL_NAME=model_container \
#     tensorflow/serving &

In [23]:
import requests, json

In [46]:
url = 'http://localhost:8501/v1/models/model_container:predict'

def make_prediction(instances):
   data = json.dumps({"instances": instances.tolist()})
   headers = {"content-type": "application/json"}
   json_response = requests.post(url, data=data, headers=headers)
   predictions = json.loads(json_response.text)['predictions']
   return np.argmax(predictions)

predictions = make_prediction(np.expand_dims(x_test[924] , axis=0))
print(predictions)

2
